### ISSUE TITLE
SEUR Tracking not working

### ISSUE THREAD

**Issue by marcolopes** [hdnpt/geartrack-website#33]
TRACKING NUMBER: **SU15260341841253**

Does not track on the geartrack
(Seur: Ainda não existe informação disponível para este ID)

Opening the LINK to SEUR SITE the TRACKING NUMBER is ONE CHAR SHORT!
http://www.seur.com/livetracking/?segOnlineIdentificador=SU1526034184125&segOnlineIdioma=pt

The correct LINK should be: http://www.seur.com/livetracking/?segOnlineIdentificador=SU15260341841253&segOnlineIdioma=pt

Maybe this explains the fail on the geartrack site.

**Comment by marcolopes** [comment]
I understand. But the SEUR link could open correctly...

Thanks for the great service!

**Comment by jonferreira** [comment]
SEUR was bought by DPD so no point now anyway

**Comment by carlosflorencio** [comment]
@jonferreira good point 👍
