### ISSUE TITLE
Gearbest EU Priority Line does not seem to be fully supported

### ISSUE THREAD

**Issue by modem** [hdnpt/geartrack-website#34]
I made an order on Gearbest with EU Priority Line. It comes by DHL from Germany. In geartrack I see the information from DHL, which seems to start showing data from Germany when DHL receives the package. But it's missing the information until Germany which I can see in https://www.1tracking.net
My tracker code starts with CF.
Let me know if it's possible to support this new shipping method or not.

**Comment by carlosflorencio** [comment]
Hi @modem, we're aware of that.

I'll try to prioritize it, thanks.

**Comment by modem** [comment]
Thanks!
