### ISSUE TITLE
4PX tracking

### ISSUE THREAD

**Issue by jonferreira** [hdnpt/geartrack-website#37]
Hi,

As far as I can see 4PX isn't supported yet.

Here's an example

http://track.4px.com/query/400204657434

**Comment by carlosflorencio** [comment]
Hi @jonferreira,

Thanks for the example, we'll try to add it ASAP.

I'll notify you when it's deployed.

**Comment by jonferreira** [comment]
Cool thanks!

I'd - try to - do it myself and submit a PR but I'm swamped right now :(

**Comment by carlosflorencio** [comment]
Hi,

Just to let you know 4PX is now live. 💪

**Comment by jonferreira** [comment]
nice!
