### ISSUE TITLE
Suggestion: Add support for Sending

### ISSUE THREAD

**Issue by miguelmanteigueiro** [hdnpt/geartrack-website#39]
https://info.sending.es/fgts/u/RZHLXV
999928686334
Ref: LPGBA000000212232590

**Comment by carlosflorencio** [comment]
We'll add to our todo list, thanks.

**Comment by carlosflorencio** [comment]
Sorry for the long wait time, we already support Sending for a few weeks now.

If you have an ID that doesn't work yet let me know. Closing for now.
