### ISSUE TITLE
Suggestion: Add auto-sort option based on last update date

### ISSUE THREAD

**Issue by jonferreira** [hdnpt/geartrack-website#40]
Hey,

Would be cool if we could get an optional "auto sort" option that would sort packages by last update date.

This way it would show all packages out for delivery first - hopefully!

Hope this makes sense

**Comment by carlosflorencio** [comment]
Hi @jonferreira good ideia, I'll add it to the todo list. 

Sorry for the delay on the v2. 

Regards

**Comment by jonferreira** [comment]
No worries :)

**Comment by vjccruz** [comment]
![image](https://user-images.githubusercontent.com/5125346/176145429-2d81591c-34e5-40c2-9b82-77a0a2bd3789.png)

I think this feature is already implemented.

**Comment by carlosflorencio** [comment]
Yeah this is already done, thanks @vjccruz :).
