### ISSUE TITLE
API is broken

### ISSUE THREAD

**Issue by luisfcorreia** [hdnpt/geartrack-website#43]
I'm getting a 400 error while inspecting console

GET https://geartrack.pt/api/ctt?id=RY402061900IL
[HTTP/2 400 Bad Request 1073ms]

**Comment by carlosflorencio** [comment]
Hi,

I can't find that ID in the CTT website: https://www.ctt.pt/feapl_2/app/open/objectSearch/objectSearch.jspx?objects=RV445876178CN&request_locale=en

**Comment by luisfcorreia** [comment]
A while ago, it used to show from more providers, not just CTT

17track dot net does show some tracking
https://t.17track.net/en#nums=RY402061900IL

**Comment by carlosflorencio** [comment]
Hi,

We've been blocked by one of our "generic" carriers. We're trying to find a good replacement in the meantime :/.

**Comment by carlosflorencio** [comment]
Closing, stale.
