### ISSUE TITLE
Nothing is working

### ISSUE THREAD

**Issue by feiticeir0** [hdnpt/geartrack-website#44]
Since the new upgrade (read it in the news) nothing is working... 
I'm following 21 track numbers and nothing appears... The progress animation it just stays there, animating without anything ever appear... 

I've tried (where I have all the numbers) in Firefox 84.0.1 (64bit) and even tried in Google Chrome, by adding a new one...

**Comment by carlosflorencio** [comment]
Sorry for this, can you check the browser console and network requests for errors? This would help us identify the issue.

**Comment by jabss** [comment]
Hi, I'm experiencing the same issue as #44 since yesterday. Tried to delete all TrackIDs and start all over but the issue remains.

![image](https://user-images.githubusercontent.com/7312250/103545672-cc54bb80-4e99-11eb-9986-70c32ee0b9c3.png)

![image](https://user-images.githubusercontent.com/7312250/103545755-eabab700-4e99-11eb-8a8b-fa70dc630a33.png)


Errors from the console:
```
Request to access cookie or storage on “<URL>” was blocked because it came from a tracker and content blocking is enabled. 80
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. geartrack.pt
[bugsnag] Loaded! notifier.js:71:20
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://tracker-api.geartrack.app/carriers/LT403651752NL. (Reason: CORS request did not succeed).

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://tracker-api.geartrack.app/carriers/LP00422259390436. (Reason: CORS request did not succeed).

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
```

It is working on the smartphone, though.

**Comment by feiticeir0** [comment]
> 
> 
> Sorry for this, can you check the browser console and network requests for errors? This would help us identify the issue.

Here it is. I'm just posting the first ones, but it's the same for all the others...
```
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. geartrack.hdn.pt
[bugsnag] Loaded! notifier.js:71:20
Loading failed for the <script> with source “https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js”. geartrack.hdn.pt:405:1
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://tracker-api.geartrack.app/carriers/LT386704016NL. (Reason: CORS request did not succeed).

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. gear.js:106:23
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://tracker-api.geartrack.app/carriers/UB185288530SG. (Reason: CORS request did not succeed).

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. gear.js:106:23
    startLoadingTracker https://geartrack.hdn.pt/js/gear.js?v=1054:106
    AsyncFunctionThrow self-hosted:678
    (Async: async)
    loadTrackToContent https://geartrack.hdn.pt/js/gear.js?v=1054:91
    addAllTracksToPage https://geartrack.hdn.pt/js/gear.js?v=1054:147
    forEach self-hosted:206
    addAllTracksToPage https://geartrack.hdn.pt/js/gear.js?v=1054:147
    <anonymous> https://geartrack.hdn.pt/js/gear.js?v=1054:6
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://tracker-api.geartrack.app/carriers/LT...4NL. (Reason: CORS request did not succeed).

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. gear.js:106:23
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://tracker-api.geartrack.app/carriers/LT.....NL. (Reason: CORS request did not succeed).

```
Thank you !

**Comment by carlosflorencio** [comment]
Should be related with CORS, I've relaxed the API allowed origin settings. Can you try again? (I've just deployed)

**Comment by feiticeir0** [comment]
> 
> 
> Should be related with CORS, I've relaxed the API allowed origin settings. Can you try again? (I've just deployed)

Nopes. Still errors:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://tracker-api.geartrack.app/carriers/S...... (Reason: CORS request did not succeed).

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. gear.js:106:23
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://tracker-api.geartrack.app/carriers/UG.....BE. (Reason: CORS request did not succeed).

[bugsnag] Event not sent due to onError callback client.js:295:21
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. gear.js:106:23
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. gear.js:106:23
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://tracker-api.geartrack.app/carriers/UG....BE. (Reason: CORS request did not succeed).

[bugsnag] Event not sent due to onError callback client.js:295:21
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. gear.js:106:23
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://tracker-api.geartrack.app/carriers/LT....NL. (Reason: CORS request did not succeed).

[bugsnag] Event not sent due to onError callback client.js:295:21
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. gear.js:106:23
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://tracker-api.geartrack.app/carriers/LT.....NL. (Reason: CORS request did not succeed).

[bugsnag] Event not sent due to onError callback client.js:295:21
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. gear.js:106:23
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://tracker-api.geartrack.app/carriers/LT.....NL. (Reason: CORS request did not succeed).

[bugsnag] Event not sent due to onError callback client.js:295:21
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://tracker-api.geartrack.app/carriers/S...... (Reason: CORS request did not succeed).

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. gear.js:106:23
[bugsnag] Event not sent due to onError callback client.js:295:21
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://tracker-api.geartrack.app/carriers/CNAKL..... (Reason: CORS request did not succeed).

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. gear.js:106:23
[bugsnag] Event not sent due to onError callback client.js:295:21
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. gear.js:106:23
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://tracker-api.geartrack.app/carriers/RE....CN. (Reason: CORS request did not succeed).

[bugsnag] Event not sent due to onError callback client.js:295:21
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. gear.js:106:23
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://tracker-api.geartrack.app/carriers/LT....NL. (Reason: CORS request did not succeed).

[bugsnag] Event not sent due to onError callback client.js:295:21
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. gear.js:106:23
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://tracker-api.geartrack.app/carriers/UG....BE. (Reason: CORS request did not succeed).

[bugsnag] Event not sent due to onError callback client.js:295:21
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. gear.js:106:23
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://tracker-api.geartrack.app/carriers/LZ...CN. (Reason: CORS request did not succeed).

[bugsnag] Event not sent due to onError callback`

**Comment by jabss** [comment]
2021/01/04 15:14 -  I'm afraid it's still with the same behavior. Same CORS errors as before.

**Comment by carlosflorencio** [comment]
Okay, I'm relaxing the `Access-Control-Request-Headers` as well. Can you guys test again? (I've just deployed again)

Also, what do you get when trying to make a request via terminal `curl -v https://tracker-api.geartrack.app/carriers` ?

**Comment by feiticeir0** [comment]
> 
> 
> Okay, I'm relaxing the `Access-Control-Request-Headers` as well. Can you guys test again? (I've just deployed again)
> 
> Also, what do you get when trying to make a request via terminal `curl -v https://tracker-api.geartrack.app/carriers` ?

I get this:
```
bvsantos@Wolverine:~$ curl  -v https://tracker-api.geartrack.app/carriers
*   Trying 146.112.61.110:443...
* TCP_NODELAY set
* Connected to tracker-api.geartrack.app (146.112.61.110) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

And a new testing yields not results :
```

notifier.js:71 [bugsnag] Loaded!
(index):405 GET https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js net::ERR_BLOCKED_BY_CLIENT
inline-script-content.js:154 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
(anonymous) @ inline-script-content.js:154
add @ jquery-3.1.1.min.js:3
(anonymous) @ jquery-3.1.1.min.js:3
each @ jquery-3.1.1.min.js:2
each @ jquery-3.1.1.min.js:2
xa @ jquery-3.1.1.min.js:3
on @ jquery-3.1.1.min.js:3
s @ jquery-sortable-min.js:3
(anonymous) @ jquery-sortable-min.js:19
(anonymous) @ jquery-3.1.1.min.js:2
map @ jquery-3.1.1.min.js:2
map @ jquery-3.1.1.min.js:2
d.fn.<computed> @ jquery-sortable-min.js:19
(anonymous) @ gear.js?v=1054:77
network-breadcrumbs.js:125 GET https://tracker-api.geartrack.app/carriers/LT479237015NL net::ERR_CERT_AUTHORITY_INVALID
(anonymous) @ network-breadcrumbs.js:125
c.fetch @ network-breadcrumbs.js:123
getCarriersForId @ gear.js?v=1054:138
startLoadingTracker @ gear.js?v=1054:97
loadTrackToContent @ gear.js?v=1054:91
(anonymous) @ gear.js?v=1054:147
addAllTracksToPage @ gear.js?v=1054:147
(anonymous) @ gear.js?v=1054:6
gear.js?v=1054:110 Uncaught (in promise) TypeError: Failed to fetch
async function (async)
startLoadingTracker @ gear.js?v=1054:97
loadTrackToContent @ gear.js?v=1054:91
(anonymous) @ gear.js?v=1054:147
addAllTracksToPage @ gear.js?v=1054:147
(anonymous) @ gear.js?v=1054:6
site.webmanifest:1 Manifest: property 'start_url' ignored, should be same origin as document.

```

**Comment by carlosflorencio** [comment]
Okay, the issue seems more related with Certificates than CORS now. The tracker-api cert was generated by Cloudflare and running a ssl test on it seems fine.

Trying to update the operative system certificates CA store is an option for you guys? In the meantime I'll try a workaround to avoid using the new domain.

**Comment by carlosflorencio** [comment]
I've changed the tracker-api url from `https://tracker-api.geartrack.app` to `https://tracker-api.geartrack.pt` on the website, can you check if it make any difference? (it will use the certificate from the `geartrack.pt` domain)

**Comment by jabss** [comment]
Working now. Thanks!

**Comment by carlosflorencio** [comment]
Cool! Since I can't replicate the issue, can you test in both domains (`geartrack.pt` and `geartrack.hdn.pt`)?

**Comment by jabss** [comment]
2021/01/04 16:33  - Tested 2 minutes ago and it failed in both domains. Retested it again (right now) and it's working on both.

**Comment by jabss** [comment]
2021/01/04 17:17  oops... not working again. Neither domain.

**Comment by carlosflorencio** [comment]
Yeah I'm making some changes on the CORS rules again but if the issue was around the certificates I wasn't expecting this to have any impact. Are you able to chat in a more straight away fashion via whatsapp/messenger/email? It will be easier to gather your feedback (if so ping me `carlosmflorencio@gmail.com`).

**Comment by feiticeir0** [comment]
Still nothing works... The same errors

**Comment by carlosflorencio** [comment]
Can you try again now? I've replaced the external tracker-api to an internal path in the same domain.

**Comment by carlosflorencio** [comment]
Since the change to use an internal path resulted in a traffic increase I'd expect this to be fixed:
![image](https://user-images.githubusercontent.com/1500881/103576013-6af91080-4eca-11eb-9813-12d423461dc7.png)

Will wait for your feedback to confirm.

**Comment by jabss** [comment]
Hi, yes, I confirm it is working now.
Thanks!

**Comment by carlosflorencio** [comment]
Cool! @feiticeir0 do you confirm as well?

**Comment by feiticeir0** [comment]
> 
> 
> Cool! @feiticeir0 do you confirm as well?

Hi ! Sorry for the delay, but I've been away .
I confirm that everything is working now ! 

Thank you very much !

**Comment by carlosflorencio** [comment]
Cool, just report here if you have more issues.
