### ISSUE TITLE
Please add this new tracker.

### ISSUE THREAD

**Issue by pedrobotelho** [hdnpt/geartrack-website#45]
Order on ebay with tracker:

https://www.orangeconnex.com/tracking?language=en&trackingnumber=EE10012419158450001040003E0N

Thanks

**Comment by carlosflorencio** [comment]
Hi @pedrobotelho, we'll try to add this tracker during the week.

Just a matter of curiosity did you have any issue like this https://github.com/hdnpt/geartrack-website/issues/44 since yesterday?

**Comment by pedrobotelho** [comment]
No Carlos, everything is working normally at my side!
I've 6 items 2 that are not working because they are from the above tracker and the other 4 are working as usually!

I did not notice any issue at all.

Thanks

**Comment by carlosflorencio** [comment]
Cool, thanks for the feedback!

**Comment by jabss** [comment]
Hi, I'm experiencing the same issue as #44 since yesterday. Tried to delete all TrackIDs and start all over but the issue remains.

![image](https://user-images.githubusercontent.com/7312250/103544668-5d2a9780-4e98-11eb-9676-5bd4be327519.png)

**Comment by carlosflorencio** [comment]
@jabss can you move your comment to the issue #44 and check if you can prove more data from you browser console / failed requests? (I can help you debug it if needed).

**Comment by carlosflorencio** [comment]
Just added this carrier :).

**Comment by pedrobotelho** [comment]
Hi Carlos!

Its working, it has the country on the stops! Great!
 
It looks great Thanks!

Just one question, maybe this is not the right place but its a simple one, on the trackers when it says Próximo ID: UJ827448XXX
the information will be display also right? we don't need to add a "new" item, right?

Thanks again

**Comment by carlosflorencio** [comment]
Hi Pedro,

Good to know it works, yeah its the next ID and it should be inserted manually at the moment. We hope to improve this process in the next version. I'll try to add a tooltip with some help when that field exists.

**Comment by pedrobotelho** [comment]
Ok thanks!

The ticket is closed and Working as expected!

Great job!
And if you need help you can count with me! Just ask!
Thanks again!
