### ISSUE TITLE
Visual enhancement

### ISSUE THREAD

**Issue by Xtema** [hdnpt/geartrack-website#46]
Hi
I noticed for the recent added 4px one of the stages is not in bold as the others
Example:
![image](https://user-images.githubusercontent.com/9453730/103548820-45561200-4e9e-11eb-8580-0c1e12c5ee7e.png)
Thanks for your great work!

**Comment by carlosflorencio** [comment]
Hi, thanks for the feedback.

I've just released some visual changes, removed the bold text and added a label for the location.

What you think?
![image](https://user-images.githubusercontent.com/1500881/103575810-266d7500-4eca-11eb-90e1-44af31f662ae.png)

**Comment by Xtema** [comment]
Hi 
It looks great 
Good job! 
Thanks for your work :)

**Comment by carlosflorencio** [comment]
Cool!
