### ISSUE TITLE
Support MRW

### ISSUE THREAD

**Issue by jonferreira** [hdnpt/geartrack-website#57]
Hi.

Would be great if support for MRW could be added. Here's an example: 08200A020901

**Comment by carlosflorencio** [comment]
Hi @jonferreira,

I've just added this new format, should work in a few minutes.

Also, if you want to try out our next version deployed at https://geartrack.app/ and provide feedback, that would be great.

We'll announce it soon, it's still a beta version where we'll be adding more features in the next days.
