### ISSUE TITLE
Add support for DHL Express shipments

### ISSUE THREAD

**Issue by CaldeiraG** [hdnpt/geartrack-website#58]
Hello there,

Can you add support for DHL Express packages? Seems like they're also doing numerical tracking codes that won't associate properly with Geartrack.

Tracking code: 8270772786 [DHL Link](https://www.dhl.com/es-en/home/tracking/tracking-express.html?submit=1&tracking-id=8270772786)

Thanks

**Comment by carlosflorencio** [comment]
Hi @CaldeiraG , I'll look into it.

**Comment by carlosflorencio** [comment]
It should work now 💪
