### ISSUE TITLE
Error logging with Github

### ISSUE THREAD

**Issue by henriqueribeiro** [hdnpt/geartrack-website#62]
I'm trying to login with my GH account but I'm getting the following error:

`{"code":500,"type":"ServerError","message":"Houston, we have a problem!"}`

Besides that, great job!! :rocket:

**Comment by carlosflorencio** [comment]
Hi @henriqueribeiro, thanks for reporting.

I can see on the logs some errors when creating a user account when coming from Github. Github might be returning a null value on a field that is mandatory for us (not sure which yet). I'll add more logging on this code path and then ask you to login again, can you do that?

**Comment by henriqueribeiro** [comment]
yes sir!

Let me know and I can try again

**Comment by carlosflorencio** [comment]
You can try again :)

**Comment by henriqueribeiro** [comment]
It's working!! That's great @carlosflorencio 
Thanks

**Comment by carlosflorencio** [comment]
Nice!
