### ISSUE TITLE
When adding the first tracking ID, prompt for postal code, when needed

### ISSUE THREAD

**Issue by jbvc97** [hdnpt/geartrack-website#68]
Hi.
First of all, great tool ❤

To track an GLS parcel, its necessary to provide an postal code, if not Geartrack can't provide information. I know i can add afterwards on the cog menu.
![image](https://user-images.githubusercontent.com/5308392/167225288-046464b5-6220-478c-a056-7152523ee467.png)

But I would suggest that, when the first tracking ID is added, should prompt the user, when needed, about the postal code [or other relevant information, maybe varies carrier to carrier, i dont know 😕], to provide the best result.

**Comment by carlosflorencio** [comment]
Yo @jbvc97 thanks for reporting, I can't seem to replicate this issue, can you describe the steps taken?

On my end, after pasting an ID (on the dialog to add a new order) the input for the postal code appears if that ID matches the regex of the carriers that require a postal code (you can check the browser requests for the carrier list compatible with that id).

**Comment by jbvc97** [comment]
Sure, i can describe the steps 😃 

- Make sure that is the first tracking id inserted in the application;
- Insert the follow tracking id: 312023328021550010, in the input;
- Click "Track".

Steps as a gif:
![msedge_ouMp83nBo9](https://user-images.githubusercontent.com/5308392/167307848-33ef5c58-4ca6-4897-882d-4f6a28cad685.gif)

After adding the ID, the app can't retrieve the information, because for this carrier (GLS) is necessary to provide the postal code.

**Comment by carlosflorencio** [comment]
Ahh 😄 yeah the first track from the homepage, I almost never use it that's why I forgot about it (I always have some IDs so I don't see the homepage that often). 

Thanks for the screencast, I'll look into requesting the postal code from that journey as well.

Thanks!

**Comment by jbvc97** [comment]
@carlosflorencio i'll close this issues because I noticed that on the homepage it already asks for the postal code. 😄

**Comment by carlosflorencio** [comment]
Thanks @jbvc97 !
