### ISSUE TITLE
Manually pick which tracking platform should be used

### ISSUE THREAD

**Issue by CaldeiraG** [hdnpt/geartrack-website#69]
Hello there, so I got a tracking number that Geartrack assumes it's on CTT which makes sense. The tracking number is [DY531671415PT](http://track.4px.com/#/result/0/DY531671415PT).

I recently found that tracking info is available on 4PX (since it's a package coming from Shenzhen) but because it's a DY code it associates as a CTT package.

My suggestion is having an option to manually switch between providers if it doesn't match with the first option. Technically you could associate DY codes with 4px and get it fixed but the flexibility of changing it whenever seems like a good call.

**Comment by carlosflorencio** [comment]
Hi @CaldeiraG ,

Thanks for the suggestion, manually selecting a carrier for an ID is something that we want to add in the future (we're focused in other projects atm so Geartrack development is a bit slow :/).

In the meantime, I've associated that ID format `DY\d{9}PT` with 4PX, if you know more formats that are missing just let me know :).
