### ISSUE TITLE
Suporte às encomendas do eBay

### ISSUE THREAD

**Issue by BanaipePT** [hdnpt/geartrack-website#7]
A meu ver acho que seria uma excelente melhoria dado a quantidade de compras que existem usando a plataforma do eBay.

Reconheço que a própria plataforma já tem um mecanismo próprio mas que nem sempre funciona e apenas fornece informações básicas.

**Formato Geral**
- HKxxxxxxxxxPY
- HKxxxxxxxxxAM
- UAxxxxxxxxxYP

**ID Para Testes**
- HK694459332PY
- HK05341163AM
- UA846098317YP

**Comment by iamfreee** [comment]
Muito obrigado @BanaipePT.

Vamos tratar de adicionar brevemente.

No futuro, para o suporte de mais IDs o repositório certo é:
https://github.com/hdnpt/geartrack

Cumprimentos

**Comment by iamfreee** [comment]
Movi para
https://github.com/hdnpt/geartrack/issues/16
