### ISSUE TITLE
CTT carrier not parsing correctly 

### ISSUE THREAD

**Issue by diogodh** [hdnpt/geartrack-website#71]
From my test (maybe others need to confirm), if you use lower case on CTT tracking, for example Rh949499356pt it will not find the shipping 
But if you use UPPERCASE like RH949499356PT it does find.
So to parse the input to uppercase at least with CTT can probably be a solution.

**Comment by carlosflorencio** [comment]
Hey @diogodh, yeah lowercase letters usage is not common in tracking ids. Even if you use that in the CTT website, they don't allow it. Some retailer sent you the id in lowercase?

Right now our regex expressions that assign ids to carriers only take in consideration the uppercase letters (valid id). If we uppercase all ids by default, it might break some carriers that use lowercase letters (can't tell by memory one that uses it).

Maybe we can add a warning message below the input when the user is user lowercase letters, it's probably an invalid id.

**Comment by diogodh** [comment]
Hello @carlosflorencio in ctt website, I can use both lower or upper case, either using website input,  short url like https://ctt.pt/t/XX123456789XX or full url like https://appserver.ctt.pt/CustomerArea/PublicArea_Detail?IsFromPublicArea=true&ObjectCodeInput=XX123456789XX&SearchInput=XX123456789XX

On the input in my case, it was a typo I did while writing the tracking code, cause my browser on mobile uses uppercase on the first letter as default.

**Comment by carlosflorencio** [comment]
Okay, I think I'll set the id regex expressions to be case insensitive. I'll let you once it's deployed. Thanks for the feedback 💪

**Comment by carlosflorencio** [comment]
Should work fine now with lowercase ids.
