### ISSUE TITLE
Login stuck

### ISSUE THREAD

**Issue by whii1Z** [hdnpt/geartrack-website#78]
Hello,

I'm stuck at login on the site, everytime I try to login it goes again for the "https://geartrack.app/login" page, even with the gmail option. I think it's the land page making it a loop.

**Comment by carlosflorencio** [comment]
Hey, could be something with the Firebase auth settings. 

Which browser are you using?

**Comment by whii1Z** [comment]
It happens on both Chrome and Opera

**Comment by carlosflorencio** [comment]
Can you check if it's working now?

**Comment by whii1Z** [comment]
Nope, fixed! Thank you so much.
